---
- name: ospf config
  hosts: devices 
  gather_facts: false
  
  tasks:
    - name: OSPF_CONFIG Process_ID and Networks
      ios_config:
        parents:
          - router ospf 100
        lines:
          - network 10.0.0.0 0.0.255.255 area 0 

  handlers:
    - name: HANDLER Config Save
      listen: config_changed
      ios_config:
        save_when: always
