---

- name: run1
  hosts: devices
  gather_facts: false

  tasks:

    - name: cmd1
      ios_config:
        parents:
          - router ospf 100
        lines:
          - net 10.0.0.0 0.0.255.255 area 0
